### ISSUE TITLE
Yaml key containing "?" dont show its menu on tmenu

### ISSUE THREAD

**Issue by gbgabo** [Calebe94/pytools#90]
**As an example of the error:**

Settings:
  Leaving?:
    Shutdown: shutdown -h now
    Restart: reboot
    Lock: i3lock-fancy
  Network: alacritty -e nmtui
  Volume: alacritty -e alsamixer
  Packages: pamac-manager
  Bluetooth: blueman-manager
  Shot: flameshot gui

**The Items inside "leaving?" are not shown on tmenu**

**Comment by calebe94** [comment]
Can't replicate.
